# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e06abd00f8a85bf7853d7b0a4d3e348b7b8cf217c18a1e41a2ed83e24efc93e1ed6efede2fd525b14dccd961f39255e385d0db36bd0b0f475cc45f1dc5fa159a

test:
  secret_key_base: d9a124c105fbeecfcea0773b8f07810fc2663cdc67906590d47b558a368cbaa212ed1aba21f58025a9a97a005d455b7aaea692e2c56c42ac6dd8436d8cc14f97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
